# Generated by Django 5.0.3 on 2024-03-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredient_remove_recipe_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
    ]
