# Generated by Django 5.0.3 on 2024-03-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
