# Generated by Django 5.0.3 on 2024-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_ingredient_delete_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(verbose_name='Image'),
        ),
    ]
