# Generated by Django 5.0.3 on 2024-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(upload_to='Recipe image', verbose_name='Image'),
        ),
    ]
