# Generated by Django 5.0.3 on 2024-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(upload_to='Recipe image', verbose_name='Image'),
        ),
    ]
